###
POST  http://localhost:3000/


###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "login":"testName",
    "password": "Password1"
}
###
GET http://localhost:3000/renew/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2E3MTE4OTlkMzZmYzNlZWFlNjFiODAiLCJuYW1lIjoidGVzdE5hbWUiLCJyb2xlIjoidGVzdFJvbGUiLCJpYXQiOjE2NzIxMjk4NTMsImV4cCI6MTY3MzQyNTg1M30.8EdZueXrtl_1lAl-mWRV9qlXFU8c9vxm1xgTbNnn1qE


###

GET http://localhost:3000/logout/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2E3MTE4OTlkMzZmYzNlZWFlNjFiODAiLCJuYW1lIjoidGVzdE5hbWUiLCJyb2xlIjoidGVzdFJvbGUiLCJpYXQiOjE2NzIxMjk4NTMsImV4cCI6MTY3MzQyNTg1M30.8EdZueXrtl_1lAl-mWRV9qlXFU8c9vxm1xgTbNnn1qE



