###
POST  http://localhost:3000/


###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "login":"testName",
    "password": "Password1"
}
###
POST  http://localhost:3000/renew
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2E3MTE4OTlkMzZmYzNlZWFlNjFiODAiLCJuYW1lIjoidGVzdE5hbWUiLCJyb2xlIjoidGVzdFJvbGUiLCJpYXQiOjE2NzIxNDkyNTcsImV4cCI6MTY3MzQ0NTI1N30.MtNgm_fYL3_y1W1qCVsbJ23NBFk2vYmrirHDl2QRDBQ"
}

###

POST  http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2E3MTE4OTlkMzZmYzNlZWFlNjFiODAiLCJuYW1lIjoidGVzdE5hbWUiLCJyb2xlIjoidGVzdFJvbGUiLCJpYXQiOjE2NzIxNDkyNTcsImV4cCI6MTY3MzQ0NTI1N30.MtNgm_fYL3_y1W1qCVsbJ23NBFk2vYmrirHDl2QRDBQ"
}



